#!/bin/bash

 rm fort.*
 ln -s *.pots fort.4
 rm *.out

 sed -i 's/ipc=0/ipc=0 nfl=-301/g' *.fres

 ../fres/source/fresco <*.fres >fresco.out

 ../fres/source/grwf <fort.301 >wf.out

 mv fort.201 elasticxs.out
 mv fort.202 transferxs.out 
 rm fort.*
 ln -s *.pots fort.4
 



##############

