#!/bin/tcsh 

set COMP = 'f90'
set PREF='a'
# change to any local preferences: 
#  copy & edit these lines yourself

if(! $?ARCH && -X arch) setenv ARCH `arch`
if( ${ARCH} == 'x86_64' ) then   
      if( -X g95 )     set COMP = 'g95'
      if( -X pgf90 )   set COMP = 'pgf90'
      if( -X pathf95 ) set COMP = 'pathf95'
      if( -X f90 ) 	set COMP = 'f90'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'i686' ) then 	# Linux Intel
      if( -X g95 )     set COMP = 'g95'
      if( -X pgf90 )   set COMP = 'pgf90'
      if( -X pathf95 ) set COMP = 'pathf95'
      if( -X ifort )   set COMP = 'ifort'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'ia64' ) then    # Linux Itanium
      if( -X ifort )   set COMP = 'ifort'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'ppc' ) then 	# Mac Powerpc
      if( -X g95 )     set COMP = 'g95'
      if( -X xlf )     set COMP = 'xlf'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'i386' ) then 	# Mac Intel
      if( -X gfortran )     set COMP = 'gfortran'
      if( -X ifort )   set COMP = 'ifort'
      if( -X f95 )     set COMP = 'f95'
      if( -X g95 )     set COMP = 'g95'
#      if( -X pgf90 )   set COMP = 'pgf90'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'sun4' || ${ARCH} == 'sun4u' ) then 	# Sun sparc
      if( -X f90 )     set COMP = 'f90'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'i86pc' ) then 	# Sun opterons
      if( -X f90 )     set COMP = 'f90'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'pwr5' ) then    # uP
      if( -X xlf90 )     set COMP = 'xlf90'
      set PREF=${ARCH}
endif
echo From arch=${ARCH}, expect compiler ${COMP}

 if ($#argv != 0)  then
 set try=$1
#if (-X ${try} && ${try} != 'fresco' && ${try} != 'sfresco' && ${try} != 'install' && ${try} !~ '-.*')  then
 if (-X ${try} && ${try} != 'fresco' && ${try} != 'sfresco' && ${try} != 'install' ) then
	set COMP = $try
	shift
 endif
 endif
set DIR = ${PREF}-${COMP}

if( ! -e ${DIR}) mkdir ${DIR}
echo Choose compiler ${COMP} in directory ${DIR}
chdir ${DIR}
echo ln -s ../*.f . >& /dev/null
ln -s ../*.f . >& /dev/null
echo \cp -f ../makefile . 
\cp -f ../makefile . 
echo make ${argv}  FC=${COMP}
make ${argv} FC=${COMP}
